# Places 5-4: Type
# Place 3: Subtype
# Places 2-1: Bits store:
# 0          0        
# Reflective Voxelize

#-- 1: Specialized --#
#- 0: Water
block.1002 = water

#- 1: Lava
block.1100 = lava

#-- 2: Full Blocks --#
#- 0:
block.2003 = iron_block diamond_block gold_block netherite_block polished_granite polished_andesite polished_blackstone_brick polished_blackstone \
polished_deepslate polished_diorite emerald_block quartz_block chiseled_quartz_block quartz_bricks quartz_pillar smooth_quartz_block amethyst_block \
copper_block chiseled_copper copper_grate cut_copper copper_bulb exposed_copper exposed_chiseled_copper exposed_copper_grate waxed_copper_block \
wexed_cut_copper waxed_chiseled_copper waxed_copper_grate waxed_copper_bulb waxed_exposed_copper waxed_exposed_cut_copper waxed_exposed_copper_grate \
waxed_exposed_copper_bulb obsidian slime_block honey_block beacon

#-- 3: Cutout --#
#- 0: Stairs
block.3000 = oak_stairs spruce_stairs birch_stairs jungle_stairs acacia_stairs dark_oak_stairs mangrove_stairs cherry_stairs bamboo_stairs \
bamboo_mosaic_stairs crimson_stairs warped_stairs stone_stairs cobblestone_stairs mossy_cobblestone_stairs stone_brick_stairs mossy_stone_brick_stairs \
granite_stairs diorite_stairs andesite_stairs cobbled_deepslate_stairs deepslate_brick_stairs brick_stairs sandstone_stairs smooth_sandstone_stairs \
red_sandstone_stairs smooth_red_sandstone_stairs prismarine_stairs prismarine_brick_stairs dark_prismarine_stairs nether_brick_stairs red_nether_brick_stairs \
blackstone_stairs end_stone_brick_stairs purpur_stairs weathered_cut_copper_stairs oxidized_cut_copper_stairs waxed_oxidized_cut_copper_stairs
block.3002 = polished_granite_stairs polished_diorite_stairs polished_andesite_stairs polished_deepslate_stairs mud_brick_stairs polished_blackstone_stairs \
polished_blackstone_brick_stairs quartz_stairs smooth_quartz_stairs cut_copper_stairs exposed_cut_copper_stairs waxed_cut_copper_stairs \
waxed_weathered_cut_copper_stairs

#- 1: Beds
block.3100 = white_bed light_gray_bed gray_bed black_bed brown_bed red_bed orange_bed yellow_bed lime_bed green_bed cyan_bed light_blue_bed \
blue_bed purple_bed magenta_bed pink_bed

#- 2: Slabs
block.3200 = oak_slab birch_slab spruce_slab jungle_slab acacia_slab dark_oak_slab mangrove_slab cherry_slab bamboo_slab bamboo_mosaic_slab \
crimson_slab warped_slab stone_slab cobblestone_slab mossy_cobblestone_slab smooth_stone_slab stone_brick_slab mossy_stone_brick_slab granite_slab \
diorite_slab andesite_slab cobbled_deepslate_slab deepslate_brick_slab deepslate_tile_slab brick_slab sandstone_slab smooth_sandstone_slab \
cut_sandstone_slab red_sandstone_slab smooth_red_sandstone_slab cut_red_sandstone_slab prismarine_slab prismarine_brick_slab dark_prismarine_slab \
nether_brick_slab red_nether_brick_slab blackstone_slab end_stone_brick_slab purpur_slab weathered_cut_copper_slab oxidized_cut_copper_slab \
waxed_weathered_cut_copper_slab waxed_oxidized_cut_copper_slab
block.3202 = polished_granite_slab polished_diorite_slab polished_andesite_slab polished_deepslate_slab mud_brick_slab polished_blackstone_slab \
polished_blackstone_brick_slab quartz_slab smooth_quartz_slab cut_copper_slab exposed_cut_copper_slab waxed_cut_copper_slab waxed_exposed_cut_copper_slab

#- 3: Doors
block.3300 = oak_door spruce_door birch_door jungle_door acacia_door dark_oak_door mangrove_door cherry_door bamboo_door crimson_door \
warped_door oak_trapdoor spruce_trapdoor birch_trapdoor jungle_trapdoor acacia_trapdoor dark_oak_trapdoor mangrove_trapdoor \
cherry_trapdoor bamboo_trapdoor crimson_trapdoor warped_trapdoor
block.3302 = iron_door iron_trapdoor

#- 4: Fences
block.3400 = oak_fence oak_fence_gate spruce_fence spruce_fence_gate

#- 5: Buttons
block.3500 = oak_button stone_button

#- 6: Pressure Plates
block.3602 = light_weighted_pressure_plate heavy_weighted_pressure_plate

#- 9: Etcetera
block.3902 = farmland anvil chipped_anvil damaged_anvil

#-- 4: Billboard meshes --#
#- 0: Grasses & Bushes
block.4000 = short_grass tall_grass fern large_fern seagrass tall_seagrass dirt_path lily_pad dead_bush firefly_bush

#- 1: Growths & Clutter
block.4100 = moss_carpet pale_moss_carpet pale_hanging_moss vine twisting_vines weeping_vines leaf_litter crimson_roots warped_roots

#- 2: Flowers & Crops
block.4200 = dandelion poppy blue_orchid allium azure_bluet red_tulip orange_tulip white_tulip pink_tulip oxeye_daisy cornflower lily_of_the_valley \
torchflower wither_rose sunflower lilac rose_bush peony pitcher_plant pink_petals wildflowers bamboo_sapling bamboo sugar_cane wheat carrots potatoes \

#- 3: Building
block.4300 = redstone_wire chain