#-- Iris Properties --#
iris.features.required = SSBO

#-- Properties --#
rain.depth = true
frustum.culling = false
occlusion.culling = false
clouds = off
shadow.enabled = false

#if (Post_Renderscale == 0.5)
    size.buffer.colortex7 = 0.5 0.5
    size.buffer.colortex8 = 0.5 0.5
    size.buffer.colortex9 = 0.5 0.5
#elseif (Post_Renderscale = 0.577)
    size.buffer.colortex7 = 0.577 0.577
    size.buffer.colortex8 = 0.577 0.577
    size.buffer.colortex9 = 0.577 0.577
#elseif (Post_Renderscale = 0.707)
    size.buffer.colortex7 = 0.707 0.707
    size.buffer.colortex8 = 0.707 0.707
    size.buffer.colortex9 = 0.707 0.707
#elseif (Post_Renderscale = 0.816)
    size.buffer.colortex7 = 0.816 0.816
    size.buffer.colortex8 = 0.816 0.816
    size.buffer.colortex9 = 0.816 0.816
#endif

blend.terrain.colortex5 = off
blend.terrain.colortex6 = off

blend.water.colortex5 = off
blend.water.colortex6 = off

blend.entities.colortex5 = off
blend.entities.colortex6 = off

blend.hand.colortex5 = off
blend.hand.colortex6 = off

#-- Texture Mapping --#
#ifdef Use2DBlueNoise
    customTexture.BlueNoiseTex = Images/Blue.png
#else
    customTexture.BlueNoiseTex = Images/STBN.bin TEXTURE_3D RGB8 128 128 64 RGB UNSIGNED_BYTE
#endif

customTexture.AlbedoAtlas = minecraft:textures/atlas/blocks.png
customTexture.SpecularAtlas = minecraft:textures/atlas/blocks_s.png
customTexture.CelestialAtlas = minecraft:textures/atlas/celestials.png
customTexture.CloudTexture = minecraft:textures/environment/clouds.png

#image.BlockAlbedo = BlockAlbedo RGBA RGBA8 UNSIGNED_BYTE true false <relativeX/absoluteX> <relativeY/absoluteY> <absoluteZ>

#-- Buffers --#
#- Voxel Map -#
# VoxelArea^3 / 8
# Max: 256^3 / 8 = 2,097,152
bufferObject.0 = 2097152

#- Voxel Data Map -#
# VoxelArea^3 * VoxelStruct
# Max: 128^3 * 32 = 67,108,864
bufferObject.1 = 67108864

#- Texture Data -#
# vec4Size * 3 (2 vec2s for sun, moon, endflash)
# Max: 16 * 3 = 48
bufferObject.2 = 48

#-- Custom Uniforms --#
uniform.vec2.ScreenSize = vec2(viewWidth, viewHeight)
uniform.int.Dimension = if(biome_category == CAT_THE_END, 2, biome_category == CAT_NETHER, 1, 0)
uniform.float.DimensionFogDensity = if(biome_category == CAT_THE_END, 0.025, biome_category == CAT_NETHER, 0.02, 0.005)
uniform.float.Pi = 3.1415926

#-- Profiles --#
profile.Default = Post_TA:4
profile.Render = Post_TA:128

#-- Screens --#
screen = <profile> [About] <empty> <empty> [Pathtracing] [Post_Processing] [Meshing] [Materials] [Lighting] [Atmosphere] [Camera] [TestFeatures]
    
    screen.About = HowTo AboutShader GetPerformance ReduceNoise ParallaxAbout BinaryPOMAbout RenderModeAbout

    screen.Pathtracing = Pathtracing_Bounces [Pathtracing_TestDists] Pathtracing_LightSamples Pathtracing_VolumeSamples 
        screen.Pathtracing_TestDists = Pathtracing_TestDists_Shadow Pathtracing_TestDists_Rough Pathtracing_TestDists_Specular

    screen.Post_Processing = Post_TA Post_Renderscale [Post_Denoising] [Post_DOF]
        screen.Post_Denoising = Post_Denoising_Volumes [Post_Denoising_Volumes]
            screen.Post_Denoising_Volumes = Post_Denoising_Volumes_Radius Post_Denoising_Volumes_Samples

        screen.Post_DOF = Post_DOF Post_DOF_Strength Post_DOF_Samples

    screen.Meshing = [Meshing_Voxels]
        screen.Meshing_Voxels = Meshing_Voxels_AreaExp

    screen.Materials = Materials_Emission Materials_NormalStrength [Materials_POM]
        screen.Materials_POM = Materials_POM Materials_POM_Distance Materials_POM_Depth Materials_POM_Samples

    screen.Lighting = 

    screen.Atmosphere = Atmosphere_SunPathRotation <empty> [Atmosphere_Sun] [Atmosphere_Moon] [Atmosphere_End_Flash] [Atmosphere_Volumes]
        screen.Atmosphere_Sun = Atmosphere_Sun_Tempurature Atmosphere_Sun_Brightness Atmosphere_Sun_Penumbra
        screen.Atmosphere_Moon = Atmosphere_Moon_Tempurature Atmosphere_Moon_Brightness Atmosphere_Moon_Penumbra
        screen.Atmosphere_End_Flash = Atmosphere_EndFlash_Brightness Atmosphere_EndFlash_Penumbra
        screen.Atmosphere_Volumes = Atmosphere_Volumes_Threshold Atmosphere_Volumes_FogDensity
    
    screen.Camera = Camera_Gamma

    screen.TestFeatures = POMAffectsDepth

#Variable Typing
sliders = \
#-- Pathtracing --# \
Pathtracing_Bounces Pathtracing_LightSamples Pathtracing_VolumeSamples \
Pathtracing_TestDists_Shadow Pathtracing_TestDists_Rough Pathtracing_TestDists_Specular \
#-- Post Processing --# \
Post_TA Post_Renderscale \
Post_Denoising_Volumes_Radius Post_Denoising_Volumes_Samples \
Post_DOF Post_DOF_Strength Post_DOF_Samples \
#-- Meshing --# \
Meshing_Voxels_AreaExp \
#-- Materials --# \
Materials_Emission Materials_NormalStrength \
Materials_POM_Distance Materials_POM_Samples Materials_POM_Depth \
#-- Lighting --# \
#-- Atmosphere --# \
Atmosphere_SunPathRotation \
Atmosphere_Sun_Tempurature Atmosphere_Sun_Brightness Atmosphere_Sun_Penumbra \
Atmosphere_Moon_Tempurature Atmosphere_Moon_Brightness Atmosphere_Moon_Penumbra \
Atmosphere_EndFlash_Brightness Atmosphere_EndFlash_Penumbra \
Atmosphere_Volumetrics_Samples Atmosphere_Volumetrics_Strength \
#-- Camera --# \
Camera_Gamma
